const sb=supabase.createClient('https://jhdezfnafhekimolfiuu.supabase.co','sb_publishable_lAfLqmLZ0rp9UZHATVXtyg_4Wmsn18i'); const $=id=>document.getElementById(id);
function tabs(w){$('signupView').classList.toggle('hidden',w!=='signup');$('loginView').classList.toggle('hidden',w!=='login');$('signupTab').classList.toggle('active',w==='signup');$('loginTab').classList.toggle('active',w==='login');$('msg').textContent=''}
$('signupTab').onclick=()=>tabs('signup');$('loginTab').onclick=()=>tabs('login');$('backLogin').onclick=()=>{$('verifyCard').classList.add('hidden');$('authCard').classList.remove('hidden');tabs('login')};
function passwordOK(p){return p.length>=8&&/[A-Z]/.test(p)&&/[0-9]/.test(p)&&/[^A-Za-z0-9]/.test(p)}
$('signupPassword').oninput=e=>{let p=e.target.value,c=[p.length>=8,/[A-Z]/.test(p),/[0-9]/.test(p),/[^A-Za-z0-9]/.test(p)];c.forEach((x,i)=>$('r'+(i+1)).classList.toggle('ok',x));let n=c.filter(Boolean).length;$('strengthBar').style.width=n*25+'%';$('strengthText').textContent=n<2?'Fraca':n<4?'Média':'Forte'};
$('signupBtn').onclick=async()=>{let name=$('name').value.trim(),email=$('signupEmail').value.trim(),phone=$('phone').value.trim(),p=$('signupPassword').value;if(!name||!email||!phone||!p)return $('msg').textContent='Preencha todos os campos.';if(phone!==$('phone2').value.trim())return $('msg').textContent='Os telefones não conferem.';if(p!==$('password2').value)return $('msg').textContent='As senhas não conferem.';if(!passwordOK(p))return $('msg').textContent='A senha ainda não atende às regras.';if(!$('terms').checked)return $('msg').textContent='Aceite os termos.';$('msg').textContent='Criando conta...';let{data,error}=await sb.auth.signUp({email,password:p,options:{data:{name,phone}}});if(error)return $('msg').textContent=error.message;if(data.session)return showPanel(data.user);$('verifyEmail').textContent=email;$('authCard').classList.add('hidden');$('verifyCard').classList.remove('hidden')};
$('loginBtn').onclick=async()=>{let{data,error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)return $('msg').textContent=error.message;showPanel(data.user)};
$('forgotBtn').onclick=async()=>{let email=$('loginEmail').value.trim();if(!email)return $('msg').textContent='Digite seu e-mail primeiro.';let{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:'https://gustavo2025001.github.io/bot-afiliados/'});$('msg').textContent=error?error.message:'Link de recuperação enviado.'};
function showPanel(u){$('authShell').classList.add('hidden');$('panel').classList.remove('hidden');let n=u.user_metadata?.name||u.email.split('@')[0];$('welcome').textContent=n+' 👋';$('sideName').textContent=n;renderProducts()}
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
const modal=$('modal'); function openProduct(){modal.classList.remove('hidden')}$('newProduct').onclick=openProduct;$('quickProduct').onclick=openProduct;$('closeModal').onclick=()=>modal.classList.add('hidden');
function getProducts(){try{return JSON.parse(localStorage.getItem('botProducts')||'[]')}catch{return[]}}
function renderProducts(){let a=getProducts();$('productCount').textContent=a.length;$('emptyHint').textContent=a.length?a.length+' produto(s)':'Cadastre o primeiro';$('productList').innerHTML=a.length?a.map((p,i)=>`<div class="row"><div class="prodIcon">${p.platform==='Shopee'?'🛍':p.platform==='Mercado Livre'?'🤝':'🟢'}</div><div><b>${esc(p.title)}</b><small>${esc(p.platform)} • ${esc(p.price)}</small></div><a href="${escAttr(p.link)}" target="_blank">Abrir link</a><button onclick="removeProduct(${i})">×</button></div>`).join(''):'<div class="empty">Nenhum produto cadastrado. Use “Novo Produto”.</div>'}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function escAttr(s){return String(s).replace(/["']/g,'')}
window.removeProduct=i=>{let a=getProducts();a.splice(i,1);localStorage.setItem('botProducts',JSON.stringify(a));renderProducts()};
$('saveProduct').onclick=()=>{let title=$('pTitle').value.trim(),price=$('pPrice').value.trim(),link=$('pLink').value.trim(),platform=$('pPlatform').value;if(!title||!link)return $('pMsg').textContent='Preencha título e link.';let a=getProducts();a.unshift({title,price:price||'Preço não informado',link,platform});localStorage.setItem('botProducts',JSON.stringify(a));$('pTitle').value=$('pPrice').value=$('pLink').value='';$('pMsg').textContent='';modal.classList.add('hidden');renderProducts()};
(async()=>{let{data}=await sb.auth.getSession();if(data.session?.user)showPanel(data.session.user)})();
